OPP: Squashed commit of the following
OPP: Handle Security Exception

Use Case:
1. Pair remote with DUT.
2. Now go to G photos application to share images.
3. Select any image and try share.
4) Cancel operation (Decline Server side)
5) And try share again.

Failure:
"Unfortunately, Bluetooth share has stopped" error comes.

Root Cause:
For security reasons, the permissions are temporary, so once the client
app.s task stack is finished, the file is no longer accessible or some
content providers don't support the read permission.

Fix:
When tap the "try again" button on the send failed dialog, the
method "BluetoothOppSendFileInfo::generateFileInfo()" will be
call, there catching Security Exception and sending empty
BluetoohSendFileInfo.

CRs-Fixed: 891628
Change-Id: I4520a91622c0532d7d0f8aeeb7ff76e9a3abe7a1

OPP: Add support for queing same file during ongoing transfer

Steps:
1. Push a file from DUT to remote.
2. while transfer is ongoing, try to push the same file
   to some other remote.

Failure:
Pop up displayed Unknown file not sent.

Fix:
Add support to send same file multiple times. Otherwise,if
same file is queued for sending after first transfer succeeds
queued instances of the same file gets removed and error is shown
as failed to send the file.

Test: Same file can be transferred successfully if queued during active
ongoing transfer.

Bug: 35014157

CRs-Fixed: 611861
Change-Id: Ic86277b4e28a93481c3b89e65644878bd644e6ff

Opp: Do not terminate session when a Batch contains an empty file

Use Case:
1) pair to remote device.
2) Send files in a batch, such that the batch
   contains an empty file in between.

Failure:
Remote rejects empty file and DUT stop sending remaining
files in queue

Fix:
If an empty file is rejected by the remote device, client session is
terminated and remaining files in the batch also marked as failure.
This change continues to send the pending files in the batch even an
empty file is rejected by the remote device. Also it provides appropriate
message to the user.

CRs-Fixed: 1019540
Change-Id: I90d06ad9f21ae387e38f076c0f16ce1d05bdf7ea

OPP: Handle Stale Data Exception

Use case:
1. Share numerous files
2. Wait for complete
3. View completed transfers
4. Before open transfer history
   click on home button
5. Repeat above steps numerous times

Failure:
Crash in com.android.bluetooth
Msg: StaleDataException, Attempting to access a
     closed Cursor Window

FATAL EXCEPTION: main
Process: com.android.bluetooth, PID: 14080
android.database.StaleDataException: Attempting to access a closed
CursorWindow.Most probable cause: cursor is deactivated prior to
calling this method.
at android.database.AbstractWindowedCursor.checkPosition
   (AbstractWindowedCursor.java:139)
at android.database.AbstractWindowedCursor.getInt
   (AbstractWindowedCursor.java:68)
at android.database.CursorWrapper.getInt(CursorWrapper.java:122)
at com.android.bluetooth.opp.BluetoothOppTransferHistory.getCleara
   bleCount(BluetoothOppTransferHistory.java:296)
at com.android.bluetooth.opp.BluetoothOppTransferHistory.onPrepare
   OptionsMenu(BluetoothOppTransferHistory.java:206)
at android.app.Activity.onPreparePanel(Activity.java:3026)
at com.android.internal.policy.PhoneWindow.preparePanel
   (PhoneWindow.java:599)

Root cause:
Some rare cases after pausing activity also cursor
is trying to fetch values from OPP DB.

Fix:
Catch Cursor Exception to avoid crash in opp profile
and break loop If we get at least one finished transfer
from DB to avoid UN necessary iterations.

Bug: 35013626

CRs-Fixed: 1105353
Change-Id: I9c76638c162e9433b0aa17b99711557ba8f9ef07

OPP: Handle Illegal Argument Exception

Usecase:
1. Power-cycle the Phone.
2. Receive a file from remote (Let it complete).
3. Open the Transfer History and select list to open received
   file.

Expected Result:
Received file can be viewed in transfer history.

Actual Result:
"Bluetooth share has stopped" is seen and file is closed
java.lang.IllegalArgumentException: Failed to find configured root that
    contains /storage/emulated/0/Bluetooth/temp.vcs
AndroidRuntime: at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:378)
AndroidRuntime: at com.android.bluetooth.opp.BluetoothOppUtility.openReceivedFile
    (BluetoothOppUtility.java:226)

Reproducibility: 1/20

Root cause:
FileProvider is responsible for adding a mapping from a name to file
system root when device boots at first time, which is not happening
in DUT in some cases leading to crash in BT OPP.

Fix:
Catch Illegal Argument Exception to avoid crash in OPP profile.

Test: Crash not observed after performing above usecase.

Bug: 35653651
Change-Id: I9824c2aa9885e14909c8f5d1f5879abd358e6c33

OPP: Optimize Power when screen is off

Usecase:
1) Transfer a big file (> 20 MB) to remote device and turn
   off screen on DUT.
2) Measure power (current consumption) during OPP usecase.

Observation:
Power measured is 130 mA or higher, exceeding KPI by 5-7 mA.

Rootcause:
When screen is off, OPP Update thread is running continuously to
read content resolver for updates. Since Screen is off, this thread
can be put to sleep for some time, to optimize power as progress
notification of ongoing transfer is not visible to user when screen
is off.

Fix:
Use power manager to know screen off/on using intents, and use the same
for sleeping of update thread.

Test: Measure power during transfer of large file when screen
is turned off. Power save of approx 5-7 mA is observed.

Bug: 36510514

CRs-Fixed: 1050330,1079150
Change-Id: Iebe852187c821933e1d72b77e37670e84230656d

OPP: Reduce buffer size for small files

Use case:
Share very small (<50 KB) file over Bluetooth.

Result:
File sharing progress status shows failed but remote device
actually received the shared file successfully.

Root Cause:
While transfer files over RFCOMM allocatiing bufer size
always as 64K which might be greater than file size being shared.

Fix:
Add check before allocating buffer size to allocate appropriately.

Bug: 35020970
Change-Id: Ia74334b6d49921423f036f55b060dab74e97edd4

Opp : Add apk,csv,ogg and ics formats as acceptable inbound types.

Use Case:
Pair with remote and receive apk, csv, ogg and ics files

Failure:
Unable to receive files with above file formats.

Fix:
Adding apk, csv, ogg and ics format as a acceptable inbound types,
to be able to receive these file formats from remote device.

CRs-fixed: 497427
Change-Id: I1d3c3b976822a9147b2b341e19b54bc16c59a94f

Opp : Clean up file when transfer is aborted by remote/local device

Use Case:
1. Send a file from OPP client to OPP Server(DUT).
2. After the incoming file notification comes up.
3. Turn Off Bluetooth and Turn on again or remove battery
   from DUT.

Failure:
- Incoming file notification still present in notification base
- If battery is removed after transfer has started then we see
  incomplete file.

Fix:
Delete File when the transfer is terminated due to
Remote's BT is turned off, remote being taken out of reach or
remote is turned off properly. Also delete the file on the next
reboot while the previous inbound transfer was interrupted by
local device power off, or battery removal.

Change-Id: I61fa66eb96dfc400eda9f8d4d3a8f538c6f05e5f

OPP : Reduce MTU size while simultaneous A2DP and OPP

Use case:
1. Start Low Latency and High Tx Power adv from the DUT
2. From a 2nd DUT scan, connect and pair with the LEP DUT
3. Connect the DUT to a SCO HS
4. Connect the DUT to 2 BR/EDR HID devices
5. Start MO call from the DUT going over SCO
6. Start sending a file from Phone over OPP to the DUT

Result:
After a while the OPP link disconnects
reason: "Connection Timeout"

Fix:
Reduce Obex MTU to 8k if A2DP/SCO are active along
with OPP connection to avoid BT RX fail.

CRs-Fixed: 879015
Change-Id: Ib68b1fd1a9c353a79e97699ab12d6253ad89078e

OPP: fix notification count display error after bt off

Use case:
1. Share numerous files
2. Turn of BT during transfer

Result:
Total file failed and success numbers will be displayed
wrongly in status bar.

Root cause:
When BT is turning off, Opp Service will update
the notification according to the file status
in database. But at that time file status is running
or pending, notification number does not include these files.
Later status Failed will be updated to opp database.
But BluetoothOppService has been destroyed and will never
update the notification again.

Fix:
Consider pending and running files as failed in
update notification when BT is turning off.

CRs-Fixed: 1088316
Change-Id: If44d2af835bf5e1b57fdccb1bea39854a8f04ef1

Opp: turn on screen once receiving incomming file

if keyguard is set to None, no one will turn on screen when
receiving incomming file. so fix it.

Change-Id: I71bd11923886782949b2296235e5d5876b53ed66
CRs-Fixed: 1104847

OPP: Broadcast incoming OPP Events to Automation APP.

Use case:
 1. Run any OPP Server Test case using QSPR
 2. Receive Incoming file request
 3. Current automation based on debug logs are sometimes
    rarely missing the event for incoming files.
Result:
 OPP Server related test cases getting failed.
Root Cause:
 Test app not able to recognize incoming file event
Fix:
 Use Broadcast of intents for test automation purpose instead
 of relying on the logs to capture event.

CRs-Fixed: 1110716
Change-Id: Icd4a1f6a6e0d64d800e5760c937f0db4ae1c3a51

Opp : Dynamic logging for OPP profile

VERBOSE level logging for OPP profile can be enabled runtime from
adb shell using following command and turn off/on BT:
setprop log.tag.BluetoothOpp VERBOSE -> VERBOSE level Logging

 Change-Id: I56d820c89015739321d8b5e121c5fc7f4a2877da

Change-Id: I4d69734ab219df60332604c1677005349c411d42